### ISSUE TITLE
swears at alias

### ISSUE THREAD

**Issue by MrOxMasTer** [conarti/eslint-plugin-feature-sliced#15]
![image](https://github.com/user-attachments/assets/dd1aa409-d80c-4642-97f0-282561b9424b)

![image](https://github.com/user-attachments/assets/de53cf20-351f-4534-b43b-7587fa6e2a71)

**Comment by conarti** [comment]
Can you provide more information and context? In which files does the error occur and in which paths?

**Comment by MrOxMasTer** [comment]
> Can you provide more information and context? In which files does the error occur and in which paths?

![image](https://github.com/user-attachments/assets/39f32511-078d-4248-a21b-15546100700b)
![image](https://github.com/user-attachments/assets/bb09cb3a-1fec-4f08-b52d-de2b5fe2aeb5)

I think I figured out how the plugin works and realized what the problem was. At first I thought I needed an absolute path based on the rule (although there was one), then I saw the relative path.
As I realized, if these files are in the same folder, then you need to use relative path. I wonder how to set my auto-imports to relative and absolute at the same time, oh well😂

**Comment by conarti** [comment]
Its ok) Yea, in "shared" with my plugin you have to use relative paths. But today it's maybe dont fully correct and you can use absolute paths also. You can add "src/shared/**/*" as "ignoreInFilesPatterns" to disable this behavior.

But I recommend thirstly to try [steiger](https://github.com/feature-sliced/steiger). And use my plugin only if you have critical issues with it
